from selenium.webdriver.common.by import By
from data.data import CreateProjectData, CreateChildProjectData, EditProjectData


class MainPageLocators:
    PHOTO_OF_THE_DAY = (By.CLASS_NAME, 'carousel-3d-container')
    DESCRIPTION_TITLE = (By.CLASS_NAME, 'description-title')
    FIRST_SLIDER_PROJECT = (By.CSS_SELECTOR, '.carousel-3d-slider > div:nth-child(1) > a')
    LAST_SLIDER_PROJECT = (By.CSS_SELECTOR, '.carousel-3d-slider > div:nth-last-child(1) > a')
    FIRST_SLIDER_PROJECT_NAME = (By.CSS_SELECTOR, 'div:nth-child(1) > a > .photos__title')
    LAST_SLIDER_PROJECT_NAME = (By.CSS_SELECTOR, 'div:nth-last-child(1) > a > .photos__title')
    SLIDER_CONFIG_BUTTON = (By.CLASS_NAME, 'projects-edit')
    SLIDER_NEXT_PROJECT_BUTTON = (By.CLASS_NAME, 'next')
    SLIDER_PREV_PROJECT_BUTTON = (By.CLASS_NAME, 'prev')
    SLIDER_CONFIG_ADD_PROJECT = (By.CSS_SELECTOR, '.modal-right__slider-item.add')
    SLIDER_COVER_INPUT = (By.ID, 'hiddenUploader')
    SLIDER_PHOTO_COUNT_RADIOBUTTON = (By.CLASS_NAME, 'switch')
    SLIDER_PROJECT_MULTISELECTOR = (By.CLASS_NAME, 'multiselect-search')
    SLIDER_MULTISELECTOR_CHOOSE = (By.ID, 'multiselect-option-57')
    SLIDER_ADD_PROJECT_SUBMIT_BUTTON = (By.CLASS_NAME, 'button')
    SLIDER_MILTISELECTOR_DROPDOWN_CLOSE = (By.CLASS_NAME, 'multiselect-dropdown')
    SLIDER_LAST_PROJECT_DELETE_BUTTON = (By.CSS_SELECTOR, 'div:nth-last-child(1) > div.delete')
    SLIDER_ALL_PROJECTS = (By.CSS_SELECTOR, '.projects .carousel-3d-slide')
    PROJECTS_LINK_FROM_DESCRIPTION = (By.CLASS_NAME, 'description-link')
    ALL_PROJECTS_BUTTON = (By.CLASS_NAME, 'projects-more')
    POTD_CURRENT_PICTURE = (By.CSS_SELECTOR, '.photos .carousel-3d-slide.current')
    POTD_NEXT_BUTTON = (By.CSS_SELECTOR, '.photos .next')
    POTD_PREV_BUTTON = (By.CSS_SELECTOR, '.photos .prev')
    PROJECT_EDIT_BUTTON = (By.CLASS_NAME, 'intro-edit')

    """Project add modal window"""
    PROJECT_ADD_BUTTON = (By.CSS_SELECTOR, '.projects-list__item.addNew')
    PROJECT_ADD_MODAL = (By.CLASS_NAME, 'projectsNew-modal')
    FULL_NAME_RU_INPUT = (By.ID, 'full-name-ru')
    FULL_NAME_EN_INPUT = (By.ID, 'full-name-en')
    SHORT_NAME_RU_INPUT = (By.ID, 'short-name-ru')
    SHORT_NAME_EN_INPUT = (By.ID, 'short-name-en')
    LOGO_INPUT = (By.ID, 'main-photo')
    LOGO_APPLY_BUTTON = (By.CLASS_NAME, 'button')
    PROJECT_START_DATE = (By.XPATH, "//input[@placeholder='Начало']")
    PROJECT_END_DATE = (By.XPATH, "//input[@placeholder='Конец']")
    NEXT_MONTH_BUTTON = (By.XPATH, "//div[@arial-label='Next month']")
    PROJECT_ADD_TODAY_DATE = (By.CLASS_NAME, 'dp__today')
    PROJECT_SELECT_DATE_BUTTON = (By.CLASS_NAME, 'dp__select')
    PARENT_PROJECT_CHECKBOX = (By.CLASS_NAME, 'checkbox')
    PROJECT_CREATE_BUTTON = (By.CSS_SELECTOR, '.actions-item.primary')
    MAIN_PAGE_PROJECTS_LIST = (By.CLASS_NAME, 'projects-list')
    SPECIFIC_PROJECT = (By.XPATH, f'//div[text()="{CreateProjectData.full_name_ru}"]')
    SPECIFIC_SUBPROJECT = (By.XPATH, f'//div[text()="{CreateChildProjectData.full_name_ru}"]')
    EDITED_SPECIFIC_SUBPROJECT = (By.XPATH, f'//div[text()="{EditProjectData.full_name_ru_edit}"]')
    PROJECT_PARENTAL_MULTISELECTOR = (By.CLASS_NAME, 'multiselect-search')
    PROJECT_PARENTAL_MULTISELECTOR_CHOOSE = (By.CSS_SELECTOR, '.multiselect-option.is-pointed')
    CLOSE_MULTISELECTOR_BUTTON = (By.CSS_SELECTOR, '.multiselect-caret.is-open')
    BUILD_MULTISELECT = (By.XPATH, '//input[@aria-placeholder="Выберите пользователей"]')
    BUILD_MULTISELECT_CHOOSE = (By.XPATH, '//li[@aria-label="Сапаров Э. Р.(emir-saparo@rambler.ru)"]')
    BUILD_MULTISELECT_ACTIVE = (By.XPATH, '//div[@aria-label="Сапаров Э. Р.(emir-saparo@rambler.ru)"]')
    BUILD_MULTISELECT_CLEAR = (By.CLASS_NAME, 'multiselect-clear')
